### PR TITLE
Ability to use custom partition key and primary keys differs from sorting keys for *MergeTree 

### PR DESCRIPTION
**Pull request by aCLr**
* _get_server_info implemented
* declarative engines parameters

### CODE REVIEW

**Comment by xzkostyan** [comment]
Я обязательно посмотрю это через недельку, как доберусь до компьютера.

**Comment by xzkostyan** [comment]
Great job.

One question: why we need `_get_server_version_info` and why it is muted in `test_parse_date_types`?

**Comment by aCLr** [comment]
`_get_server_version_info` appears in my code before [that](https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/f3e30ea4e75d74b39862bdef762e33be1e0b6476) commit. The problem was that `DESCRIBE TABLE` returns different number of columns in different versions. Don't remember, what was the solution, but `_get_server_version_info` was needed. Anyway, there is no reason not to retrieve that info.

That method muted for `test_parse_date_types` because ALL requests to localhost:8123 will return specified response. As you can see, the response `a\nDate\n2012-10-25\n` is incorrect server version :)


P.S. If you going to make a new release... I'm going to make several new pull requests (joins, engines reflection and maybe something else) in a short time. Maybe you want to wait for it.

**Comment by xzkostyan** [comment]
It seems that [the problem](https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/43) with `DESCRIBE TABLE` was fixed in this commit: https://github.com/xzkostyan/clickhouse-sqlalchemy/commit/f3e30ea4e75d74b39862bdef762e33be1e0b6476

Take your time with making PRs. There is no need to hurry. I'm planning to make new release by the end of March.

**Comment by aCLr** [comment]
Yep, I've seen it. 
If there is no reason to have that method implemented it can be removed, of sure. But it is the part of SQLA-engines API, so I think that it can exist in that dialect.

**Pull request merged**
