### PR TITLE
Sa 2.0

### LINKED ISSUE #242: Support for Sqlalchemy 2.0?
@xzkostyan is there any plan for supporting Sqlalchemy 2.x (released in Jan 2023)

I just updated my sqlalchemy from 1.4 to 2.0.3 and faced this error

```
ImportError: cannot import name '_bind_or_error' from 'sqlalchemy.sql.base' 
```

### PR DESCRIPTION
**Pull request by PedroAquilino**
- fixes #242

- fixes #<issue number>

Checklist:

- [x] Add tests that demonstrate the correct behavior of the change. Tests should fail without the change.
- [x] Add or update relevant docs, in the docs folder and in code.
- [x] Ensure PR doesn't contain untouched code reformatting: spaces, etc.
- [x] Run `flake8` and fix issues.
- [x] Run `pytest` no tests failed. See https://clickhouse-sqlalchemy.readthedocs.io/en/latest/development.html.

### CODE REVIEW

**Comment by thomas-brandstaetter** [comment]
I would avoid changing oneliners into multiple lines w/o a reason

from original version: `foo(bar=baz)`
into `foo(
    bar=baz
)`

Makes it very much harder to assess these changes.

**Comment by thomas-brandstaetter** [comment]
I would avoid changing one-liners into multiple lines w/o a reason.

Changing `foo(bar=baz)` into `foo(
     bar=baz
)`
makes it very much harder to assess these commits.

**Comment by Net-Mist** [comment]
Hello, 
thanks a lot for your work, we were looking to move to sqlalchemy 2 for a long time :) 

I tested your code, and have a bug. When importing `import clickhouse_sqlalchemy.types` I get 
```
ImportError: cannot import name '_bind_or_error' from 'sqlalchemy.sql.base' ([...]/python3.11/site-packages/sqlalchemy/sql/base.py)
```

Indeed, your code [is still using _bind_or_error](https://github.com/usizy/clickhouse-sqlalchemy/blob/sa-2.0/clickhouse_sqlalchemy/sql/schema.py#L3) whereas it doesn't exist anymore in sqlalchemy 2. FYI, in v1.4, the function has a deprecated warning:  "The ``bind`` argument for schema methods that invoke SQL against an engine or connection will be required in SQLAlchemy 2.0."

**Comment by PedroAquilino** [comment]
Thanks @Net-Mist I check how to remove the reference to _bind_or_error

**Comment by Net-Mist** [comment]
Hello,
I found another regression with Lambda function. 

This code works:
```python
from clickhouse_sqlalchemy.ext.clauses import Lambda
from sqlalchemy import func

toUInt32 = text("x -> toUInt32(x)")
print(func.arrayMap(
    toUInt32, func.splitByChar(",", func.trim(text("BOTH '{}' FROM foo.bar")))
)) 
```

but this code doesn't (and it was working with SA 1)
```python
from clickhouse_sqlalchemy.ext.clauses import Lambda
from sqlalchemy import func

toUInt32 = Lambda(lambda x: func.toUInt32(x))
print(func.arrayMap(
    toUInt32, func.splitByChar(",", func.trim(text("BOTH '{}' FROM foo.bar")))
)) 
```

**Comment by Net-Mist** [comment]
Hello !

I found another issue. In file `clickhouse_sqlalchemy/ext/clauses.py`, in the __init__ of Lambda class, we need to replace `util.callable` to `callable`. Indeed sqlalchemy >= 2.0 doesn't provide this function anymore as it is now in python since 3.2

**Comment by PedroAquilino** [comment]
I have changed the call to util.callable to the builtin callable

**Comment by m-alhajji** [comment]
Hi. Is there anything blocking this at the moment? Has people migrated to a different tool? Can I be of any help?

**Comment by xzkostyan** [comment]
Now tests are not green even after fixing lint errors: https://github.com/xzkostyan/clickhouse-sqlalchemy/actions/runs/6266313792/job/17017005243

**Comment by xzkostyan** [comment]
Thank you. SQLAlchemy 2.0 support was released in 0.3.0.

**Pull request closed without merging**
