### PR TITLE
Support for "sqlalchemy.sql.expression.extract" construct

### PR DESCRIPTION
**Pull request by gribanov-d**
When you want to extract year, month or day from Date field.

### CODE REVIEW

**Comment by xzkostyan** [comment]
Hi,

This PR looks like good feature. Please, add test for it in `tests/test_select.py`.

**Comment by xzkostyan** [comment]
BTW, you can use `func.toYear(...)` or `func.toMonth(...)` proxies.

**Comment by gribanov-d** [comment]
Thanks. I will add tests and update this PR.

**Comment by gribanov-d** [comment]
We need EXTRACT for Cubes [https://cubes.readthedocs.io/en/latest/backends/sql.html#date-data-type](https://cubes.readthedocs.io/en/latest/backends/sql.html#date-data-type)

**Comment by xzkostyan** [comment]
Please resolve conflicts: ClickHouseCompiler was moved from src/base.py to src/drivers/base.py. Everything else looks good.

**Pull request merged**
