### PR TITLE
final clause

### PR DESCRIPTION
**Pull request by sdrenn**
FINAL modifier added
[https://clickhouse.tech/docs/ru/query_language/select/#select-from-final](url)

### CODE REVIEW

**Comment by xzkostyan** [comment]
Good job!

**Comment by ods** [comment]
How does it work for JOIN-s, select from what table will be FINAL-ized?

And why not just use standard SQLAlchemy way for such cases `with_hint()` method? It requires just 2 lines in compiler:

```
    def get_from_hint_text(self, table, text):
        return text
```

Usage:

```
table.select().with_hint(table, 'FINAL')
```

**Comment by xzkostyan** [comment]
It seems than `FINAL` clause [makes sense](https://clickhouse.tech/docs/en/single/#select-from-final) only in selecting from single table with *mergetree engine.

According to [docs](https://clickhouse.tech/docs/en/single/#select-queries-syntax) `FINAL` clause should be rendered after `FROM ....` and before any `JOIN`s.

Currently `FINAL` will be rendered after `JOIN`s:

```python
q1 = self.session.query(table.c.x).subquery()
q2 = self.session.query(table.c.x).subquery()

print(self.session.query(q1.c.x, q2.c.x).join(q2, q1.c.x == q2.c.x).final())
```

```sql
SELECT anon_1.x AS anon_1_x, anon_2.x AS anon_2_x FROM (SELECT t1.x AS x FROM t1) AS anon_1 INNER JOIN (SELECT t1.x AS x FROM t1) AS anon_2 ON anon_1.x = anon_2.x FINAL
```

Which is obviously incorrect. But even it will render in proper place ClickHouse server will throw error:

```sql
:) select * from (select number as x from system.numbers limit 10) as a final join (select number as x from system.numbers limit 10) as b on a.x = b.x;

SELECT *
FROM 
(
    SELECT number AS x
    FROM system.numbers
    LIMIT 10
) AS a
FINAL
INNER JOIN 
(
    SELECT number AS x
    FROM system.numbers
    LIMIT 10
) AS b ON a.x = b.x

Received exception from server (version 20.3.2):
Code: 181. DB::Exception: Received from localhost:9000. DB::Exception: Illegal FINAL. 

0 rows in set. Elapsed: 0.005 sec. 
```

In both cases we will get an error.

Yes, `with_hint` can be used for `FINAL` rendering. But it's designed [for other purposes](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.with_hint). It is flexible (I believe that hints are escaped) but imho `.final()` looks way more natural.

**Comment by ods** [comment]
> In both cases we will get an error.

It does work when properly formed. At least the following test passes: https://github.com/ods/aiochsa/blob/master/tests/test_execute.py#L306-L332

**Comment by xzkostyan** [comment]
Oh, I see. Now I understand your point. https://github.com/xzkostyan/clickhouse-sqlalchemy/issues/95

**Pull request merged**
